Convert to Polymer 3, add events type definitions
vaadin/vaadin-tabs pull request #183
Opened 2020-12-08 08:11 UTC by web-padawan

Fixes #182 

Note: will merge `3.2` to master once the [build](https://travis-ci.org/github/vaadin/vaadin-tabs/builds/748290934) passes and then update the base branch.

2020-12-10 15:22 UTC, alvarezguille requested changes
Demo resources were converted an left, should they be removed @web-padawan

2020-12-10 15:25 UTC, alvarezguille commented on theme/lumo/vaadin-tabs-styles.js
> +      /* For IE11 */
Is this still needed?

2020-12-11 07:41 UTC, web-padawan commented on theme/lumo/vaadin-tabs-styles.js
> +      /* For IE11 */
Removed.

2020-12-11 07:55 UTC, tomivirkki approved these changes

2020-12-11 08:07 UTC, merged